generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Product
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: product
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        is_active:
          label: Active
        is_on_main:
          label: 'On main'
        is_material:
          label: Material
        dm_gallery: Gallery
      list:
        display:
          - '=title'
          - category_id
          - logo_id
          - sort
          - is_active
          - is_on_main
          - is_material
        sort:
          - title
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - title
          - is_active
          - is_on_main
          - is_material
          - description
          - logo_id
          - sort
          - category_id
          - agent
          - agent_text
      form:
        display:
          NONE: [title, is_active, is_on_main, is_material, category_id]
          Logo: [logo_id_form, logo_id_view]
          Description: [description]
          'Agent text': [agent_text]
          Gallery: [dm_gallery]
          Others: [sort, agent]
        class: ProductAdminForm
        fields: {  }
      edit: ~
      new: ~
